---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
spec:
  selector:
    app.kubernetes.io/name: drone-server
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 80
    #   - name: https
    #     protocol: TCP
    #     port: 4443
    #     targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  labels:
    app.kubernetes.io/name: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-server
    spec:
      containers:
      - name: server
        image: drone/drone:1.6.5
        env:
        - name: DRONE_DATABASE_DRIVER
          value: mysql
        - name: DRONE_USER_FILTER
          value: octocat # You have to update
        - name: DRONE_SERVER_PORT
          value: ":80"
        - name: DRONE_SERVER_PROTO
          value: https
        - name: DRONE_SERVER_HOST
          value: example.ngrok.io # You have to update
        - name: DRONE_DATABASE_DATASOURCE
          valueFrom:
            secretKeyRef:
              name: drone-server
              key: drone-database-datasource
        - name: DRONE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: drone-server
              key: drone-github-client-id
        - name: DRONE_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-server
              key: drone-github-client-secret
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-server-rpc
              key: drone-rpc-secret
